version: '3.7'

services:
    app:
        build:
            context: .
            dockerfile: .docker/Dockerfile
            args:
                progress: plain
        image: animasiku-web-server:1
        container_name: animasiku-app
        restart: always
        environment:
            - TZ=Asia/Jakarta
        ports:
            - 8282:80
        volumes:
            - ./www:/var/www/html
        depends_on:
            - mariadb
        networks:
            - animasiku-network

    mariadb:
        image: mariadb:10.6.8
        volumes:
            - vol-mariadb:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "secret"
            MYSQL_USER: "myuser"
            MYSQL_PASSWORD: "mypass"
            MYSQL_DATABASE: "mydb"
        restart: always
        networks:
            - animasiku-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        environment:
            UPLOAD_LIMIT: "750M"
        links:
            - mariadb:db
        ports:
            - 8181:80
        depends_on:
            - mariadb
        networks:
            - animasiku-network

networks:
    animasiku-network:

volumes:
    vol-mariadb:
